### ISSUE TITLE
App Won’t Update Past 1248

### ISSUE THREAD

**Issue by paulrehkugler** [paulrehkugler/xkcd#74]
Some users cannot access comics more recent than 1248. As far as I can tell, https://xkcd.com/1248/info.0.json and https://xkcd.com/1249/info.0.json both have well-formed JSON, so this may be a local issue with the app.

**Comment by zelbrium** [comment]
I've been experiencing this issue since I got a new iPhone with iOS 12. I looked through the code of the app a bit a few months ago, but I wasn't able to find the problem. Unfortunately this lead me to switch to the xkcd: os app, but I don't like it -- I'd love to go back to your app if this issue gets fixed! I'll take a look at the code again tonight and see if I can find anything.

**Comment by zelbrium** [comment]
Okay, I actually ran it on the iOS emulator this time instead of just looking at the code. The high-level blame is this line:

https://github.com/paulrehkugler/xkcd/blob/2bad993731b0e3be74f9f4c20c0a1591f1ab9abd/Classes/FetchComicFromWeb.m#L74

Removing that function call (replacing it with `NSData *fixedData = data;` for example) fixes the problem and comics can load past 1248. Clearly something about the json for comic 1249 breaks that function's algorithm. I'll keep investigating.

**Comment by paulrehkugler** [comment]
Thanks so much for your help! This should be fixed with PR #75.
